### PR TITLE
Addition of awesome new incomplete block logging

### PR DESCRIPTION
**Pull request by kezz**
More to come! This was because iKeirNez wanted me to commit how I've got :)

### CODE REVIEW

**Comment by keir-nellyer** [comment]
Looks awesome so far! Good job!

**Comment by kezz** [comment]
I'm quite new to SQL so if you could make sure all my syntax is ok that'd be awesome! I just got a few lessons recently from a family friend who works in that industry so it all should be fine but if you could keep an eye on that I'd be very grateful :D

**Comment by keir-nellyer** [comment]
@kezz101 Sure I'll do my best to keep on the look out, when I have time I'll be sure to give you a hand. I really appreciate all the work you have been doing on CommandsEX recently. I wanted Release 2.0 to be a big update and it started off fine but I have gotten a bit bogged down with other work (school and stuff).

**Comment by kezz** [comment]
@iKeirNez Thanks! And I understand :)

**Comment by keir-nellyer** [comment]
@kezz101 Hopefully soon I can start some real work on CommandsEX soon!

**Comment by kezz** [comment]
:)

**Pull request merged**
