### PR TITLE
Added '/urbandictionary' and tags to broadcast

### PR DESCRIPTION
**Pull request by kezz**
/urbandictionary will fetch the definition of a word from the Urban Dictionary

The extra tags to /broadcast are as follows:
-p = will display the players name instead of [Broadcast]
-t = will allow the user to use a custom tag

### CODE REVIEW

**Comment by keir-nellyer** [comment]
This is very cool! Good job Kezz101! Will merge and test!

**Comment by kezz** [comment]
Should all work. I did test it!

**Comment by keir-nellyer** [comment]
Nice, about to test

**Comment by kezz** [comment]
I'm eager to know how it goes! Bear in mind that due to limitations with the Urban Dictionary API you can only define one word definitions.

**Comment by keir-nellyer** [comment]
I tested it and it works apart from the fact that it doesn't take new lines, Where it should be a new line it has a \r and the weird thing is that I tried: System.out.println(def.replaceAll("\r", "\n"));
but the /r's remain. This makes me think that the \r's are actually characters that cannot be displayed.

I am also about to send another commit with some minor changes :)

**Comment by kezz** [comment]
Well what I can do is send it through an anti-inploder I shall add to Utils and set '\r' as the split...

**Comment by keir-nellyer** [comment]
Hmmm I tried that too but I think \r is actually a character or something and for some reason it can't display so instead it displays \r. Not completely sure though.

**Comment by kezz** [comment]
Hmm... So it just displays \r in the chat?

**Comment by keir-nellyer** [comment]
It would display something like this

GMail is a mailing system\rDeveloped by Google Inc.\rIt's awesome!

**Comment by kezz** [comment]
OH! \ in Java ignores the next charactor if it is somthing special like ". You'll need to do        System.out.println(def.replaceAll("\r", "\n"));

**Comment by kezz** [comment]
*two slashes

**Comment by keir-nellyer** [comment]
Ok thanks, will try that!

**Comment by keir-nellyer** [comment]
Fixed this issue, had the escape the backslash by using def.replaceAll("\\r", "\n");

**Comment by kezz** [comment]
Awkward how github removes //

**Comment by keir-nellyer** [comment]
Does it? Doesn't do it for me. Also you will need to update your github repo for the new code I added.

**Comment by kezz** [comment]
How do I go around doing this? Re-forking?

**Pull request merged**
