### PR TITLE
Addition of awesome new Email features

### PR DESCRIPTION
**Pull request by kezz**
By moving from Java Mail to the Apache Commons Mail I have added new features!
- There are now three types of email
  - Simple Email (basic text)
  - Attachment Email (basic text with attachments)
  - HTML Email (html text)
- You can set the to, cc and bcc of an email.
- You can set the bounceback address!
- You can see a list of who the email is sent to
- Email authentication (username and password). This means you can now send E-Mails from any provider (e.g GMail)

This update is aimed at making it more server friendly. E.G A server owner can use this email to E-Mail players of new updates. Players could register for the website via the game. 

P.S There is a few 'unchecked' errors in the Utils section of the Email Helper. I have also moved over to JRE1.7 to enable switching of Strings.

### CODE REVIEW

**Comment by keir-nellyer** [comment]
That is very nice, whats even better is I don't think we need the Apache Commons JAR as Apache Commons is built into Bukkit!

**Comment by keir-nellyer** [comment]
Ok, I was wrong, the JAR is required

**Comment by kezz** [comment]
Oh right... That's a shame!

**Comment by keir-nellyer** [comment]
Yeah, kinda annoying but o well!

**Pull request merged**
